### ISSUE TITLE
response_model=Union[...] fails mypy type checking

### ISSUE THREAD

**Issue by dp-rufus** [tiangolo/fastapi#2279]
I'm having a problem using a `Union` type as my `response_model`.

See the example here: https://fastapi.tiangolo.com/tutorial/extra-models/#union-or-anyof

This example runs correctly:
```
$ uvicorn test:app &
$ curl -q http://localhost:8000/items/item1
{"description":"All my friends drive a low rider","type":"car"}
```

But when I check it with mypy:
```
$ mypy test.py 
test.py:33: error: Argument "response_model" to "get" of "FastAPI" has incompatible type "object"; expected "Optional[Type[Any]]"
Found 1 error in 1 file (checked 1 source file)
```

This seems to be a regression - but I am not sure whether the root cause is FastAPI or mypy (or something else)?

### Environment

Python 3.8.6
FastAPI 0.61.1
pydantic 1.6.1
mypy 0.790

### Related issues
https://github.com/tiangolo/fastapi/issues/86#issuecomment-476344321

**Comment by dp-rufus** [comment]
Bisected this down to mypy 0.770 (works) / mypy 0.780 (fails)

Possibly introduced by https://github.com/python/mypy/pull/8779 ?

**Comment by dp-rufus** [comment]
A possible workaround seems to be to use a [constrained type alias](https://www.python.org/dev/peps/pep-0484/#type-aliases) instead of a `Union`:

So the example from the FastAPI docs above becomes:
```py
EitherItem = TypeVar('EitherItem', PlaneItem, CarItem)


@app.get("/items/{item_id}", response_model=EitherItem)
    ...
```

The new code...
- runs correctly
- checks successfully with the latest mypy (0.790)
- becomes an `anyOf` in swagger

**Comment by Mause** [comment]
Well that is far from ideal - what point does Union have at that point?

**Comment by dp-rufus** [comment]
Perhaps someone who knows more type theory than me can confirm whether these two constructs are indeed equivalent? I find it a little strange that one works but the other does not, if they have the same meaning.

**Comment by dp-rufus** [comment]
> Well that is far from ideal - what point does Union have at that point?

Looks like we can still use Union if we use @dmontagu's [Inferring Router](https://fastapi-utils.davidmontague.xyz/user-guide/inferring-router/) from fastapi-utils.

But then - in the example from the documentation - we would need to unmarshal the result by hand rather than just returning a dict:

```py
@router.get("/items/{item_id}")
async def read_item(item_id: str) -> Union[PlaneItem, CarItem]:
    items_ = parse_obj_as(Dict[str, Union[PlaneItem, CarItem]], items)
    return items_[item_id]
```

**Comment by xmatthias** [comment]
I'm running into this as well...

@dp-rufus , did you open an issue on the mypy repository to ask about this ... ? 

to me, this seems like a bug in mypy in conjunction with `Union`, as i don't think they'd want to break this behaviour / check...

**Comment by dp-rufus** [comment]
Well spotted @xmatthias! I didn't see that pydantic issue.

I agree it looks like `TypeForm[T]` will fix this when it gets added to mypy.

**Comment by xmatthias** [comment]
I guess your `EitherItem = TypeVar('EitherItem', PlaneItem, CarItem)` would fix the problem either ... but honestly, i'm not sure what the sideeffects of this might be

**Comment by xmatthias** [comment]
Since the mypy upgrade to 0.800, the `TypeVar` workaround seems to be broken.

Unfortunately, with both `Union[]` and `TypeVar` broken, i'm currently at a loss on how this can be worked around.

**Comment by xmatthias** [comment]
The seemingly correct answer is to use pydantic's [`__root__` type ](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types).


I've found this answer in in another issue here https://github.com/tiangolo/fastapi/issues/518#issuecomment-576629657

This works for the latest mypy (0.812 at the time of writing) - and the response-model in swagger UI is also shown correctly as one of the 2.

based on the above example with `EitherItem`, this would then look as follows:

``` python
from typing import Union

from pydantic import BaseModel


class PlanetItem(BaseModel):
    id: str
    planet_name: str 
    # ...

class CarItem(BaseModel):
    id: str
    name: str
    # ...

class EitherItem(BaseModel):
    __root__: Union[PlanetItem, CarItem]


@app.get("/items/{item_id}", response_model=EitherItem)
def get_items(item_id):
    pass
```

**Comment by dp-rufus** [comment]
Thanks for the update!

I suppose we could do this
```python
@app.get("/items/{item_id}", response_model=EitherItem)
def get_items(item_id):
   # response = whatever
    return EitherItem.parse_obj(response)
```
to avoid explicitly using `__root__`

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

I think this was solved some time ago in some FastAPI version. Could you check again with a recent version?

If that solves the original problem, then you can close this issue @dp-rufus  ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by shayanhoshyari** [comment]
I suspect the problem is usage of `Dict`. Using `Mapping` type hint can possibly can solve the issue. Mapping is covariant, but Dict is not (mainly due to the fact that Dict is mutable and Mapping is not). It means that `Dict[int, object]` is not a subtype of `Dict[int | str, object]`. However, `Mapping[int, object]` is subtype of `Mapping[int | str, object]`
